# Competitive Blog Generator Configuration
# 🎛️ USER-FRIENDLY SETTINGS - Non-technical users can adjust all parameters

# ===== AI MODEL SETTINGS =====
llm:
  model: "llama-3.3-70b-versatile"  # AI model to use
  temperature: 0.6               # Creativity (0.0=factual, 1.0=creative)
  max_tokens: 2000              # Response length limit

# ===== RESEARCH DEPTH SETTINGS =====
search:
  max_results: 10                    # Results per search query
  
  # 🎯 4-CATEGORY SEARCH SYSTEM
  # Choose how many searches to perform for each category
  # Focus areas will select which 4 categories to use
  category_1_searches: 3             # Searches for focus_areas[0]
  category_2_searches: 3             # Searches for focus_areas[1] 
  category_3_searches: 2             # Searches for focus_areas[2]
  category_4_searches: 2             # Searches for focus_areas[3]
  
  news_results: 5                   # How many news articles (separate from categories)
  enable_deep_research: true        # Enable comprehensive research
  
# ===== CONTENT GENERATION SETTINGS =====
blog:
  min_word_count: 2000              # Minimum article length
  max_word_count: 4000              # Maximum article length
  style: "informative"             # Options: informative, casual, professional, technical
  target_audience: "females"        # Options: general, professionals, beginners, experts
  include_sources: true             # Include source citations
  include_data: true                # Include statistics and data
  include_citations: true           # Add reference links
  competitive_positioning: true     # Enable competitive analysis
  
# ===== AGENT BEHAVIOR SETTINGS =====
agents:
  strategy:
    analysis_depth: "comprehensive"    # Options: basic, detailed, comprehensive
    competitive_focus: true            # Analyze competitor positioning
    target_audience_analysis: true     # Deep audience analysis
    content_angle_generation: 3        # Number of unique angles to generate
    market_gap_identification: true    # Find market opportunities
    strategic_positioning: true        # Define unique market position
  research:
    max_sources: 15                # Maximum research sources
    
    # 🎯 FOCUS AREAS: Select 4 categories for research
    # The system will use these 4 categories with the search counts above
    #
    # AVAILABLE CATEGORIES:
    # - "market_trends": Market analysis, industry outlook, future trends
    # - "competitor_analysis": Top companies, competitive landscape, leading solutions
    # - "industry_news": Latest news, recent developments, industry updates
    # - "data_points": Statistics, market size data, growth metrics, surveys
    # - "research": Academic studies, case studies, white papers, research
    # - "tips": How-to guides, best practices, implementation tips
    # - "solutions": Tools, software, platforms, practical solutions
    # - "youtube_research": Video tutorials, reviews, guides from YouTube
    #
    # EXAMPLES:
    # Business focus: ["market_trends", "competitor_analysis", "industry_news", "data_points"]
    # Educational focus: ["research", "tips", "solutions", "youtube_research"]  
    # Mixed focus: ["market_trends", "tips", "solutions", "industry_news"]
    #
    # SEARCH MAPPING:
    # focus_areas[0] gets category_1_searches (3 searches)
    # focus_areas[1] gets category_2_searches (3 searches)
    # focus_areas[2] gets category_3_searches (2 searches) 
    # focus_areas[3] gets category_4_searches (2 searches)
    #
    focus_areas: ["market_trends", "competitor_analysis", "industry_news", "data_points"]
    timeout_seconds: 300           # Research timeout
    strategy_guided: true          # Use strategy agent guidance
    primary_keywords: 3                # Number of primary keywords
    secondary_keywords: 8              # Number of secondary keywords
    search_intent_analysis: true       # Analyze user search intent
    competitor_keyword_analysis: true  # Research competitor keywords
    content_structure_optimization: true # Optimize heading structure
    meta_tags_generation: true        # Generate meta descriptions and titles
  writer:
    word_count_target: 2500        # Target word count
    unique_angle_required: true     # Require unique perspective
    include_examples: true          # Include real examples
    seo_guided: true               # Use SEO agent recommendations
    strategy_aligned: true         # Follow strategy agent direction
  editor:
    seo_optimization: true          # Enable SEO optimization
    competitive_review: true        # Review competitive positioning
    readability_check: true        # Check readability
    keyword_density_check: true    # Verify keyword optimization
    meta_description_generation: true # Generate meta descriptions
    final_strategy_alignment: true # Ensure final content matches strategy

# ===== MONITORING & OUTPUT SETTINGS =====
monitoring:
  verbose_progress: true            # Show detailed progress
  log_api_calls: false             # Log API interactions
  show_research_summary: true      # Display research findings
  
output:
  format: "markdown"               # Output format
  include_metadata: true           # Add generation metadata
  save_research_data: true         # Save research to separate file
  timestamp: true                  # Include timestamp in filename
  
# ===== RATE LIMITING SETTINGS =====
rate_limiting:
  llm_delay_seconds: 2            # Delay between AI calls
  search_delay_seconds: 1         # Delay between searches
  max_retries: 3                  # Maximum retry attempts
  backoff_multiplier: 2           # Exponential backoff factor